# Generated by Django 4.2.9 on 2024-03-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_id',
        ),
    ]
