# Generated by Django 4.2.9 on 2024-03-13 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
