# Generated by Django 4.2.9 on 2024-03-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_watchlist_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_state',
            field=models.BooleanField(default=True),
        ),
    ]
